import '../../public/css/reset.css';
import '../../public/css/index.css';
import { AppRecoilRoot } from './components/recoil/RecoilRoot';
import { ModalContainer } from './components/modals/ModalContainer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AppRecoilRoot>
          {children}
          <ModalContainer />
        </AppRecoilRoot>
      </body>
    </html>
  );
}
