import '../../public/css/reset.css';
import '../../public/css/index.css';
import { AppRecoilRoot } from './components/recoil/RecoilRoot';
import { ModalContainer } from './components/modals/ModalContainer';
import { NavBar } from './components/NavBar/NavBar';
import { layout, main } from './layout.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AppRecoilRoot>
          <div className={layout}>
            <div className={main}>{children}</div>
            <NavBar />
          </div>
          <ModalContainer />
        </AppRecoilRoot>
      </body>
    </html>
  );
}
